packages:
  - docs
  - packages/*

catalog:
  '@ai-sdk/anthropic': 3.0.1
  '@ai-sdk/google': 3.0.1
  '@ai-sdk/openai': 3.0.1
  '@logtape/logtape': ^1.3.5
  '@napi-rs/keyring': ^1.2.0
  '@optique/core': ^0.8.3
  '@optique/logtape': ^0.8.3
  '@optique/run': ^0.8.3
  '@standard-community/standard-json': ^0.3.5
  '@standard-schema/spec': ^1.0.0
  '@types/node': ^20.19.9
  '@valibot/to-json-schema': ^1.5.0
  ai: 6.0.3
  dom-serializer: ^2.0.0
  domhandler: ^5.0.3
  htmlparser2: ^10.0.0
  js-tiktoken: ^1.0.21
  linkedom: ^0.18.12
  '@mozilla/readability': ^0.6.0
  tsdown: ^0.18.3
  typescript: ^5.9.3
  valibot: 1.2.0
  zod: 4.2.1

engineStrict: true

nodeVersion: 20.19.0
