packages:
- packages/*

catalog:
  "@ai-sdk/anthropic": ^3.0.1
  "@ai-sdk/google": ^3.0.1
  "@ai-sdk/openai": ^3.0.1
  "@logtape/logtape": ^1.3.5
  "@standard-schema/spec": ^1.0.0
  "@types/node": ^20.19.9
  ai: ^6.0.3
  tsdown: ^0.18.3
  typescript: ^5.9.3

engineStrict: true
nodeVersion: 20.19.0
